:: UPDATE THESE LINES ACCORDING TO YOUR PROJECT STRUCTURE

set PRIVATE_KEY_PATH="C:\ssh\kingfishair.pem"

set SITE_DOMAIN="kingfishair.progmasters.hu"

set SERVER_USER="ubuntu"

set FRONTEND_DIR="./kingfishair_frontend"

set BACKEND_BUILD_DIR="./target"

set FRONTEND_BUILD_DIR="%FRONTEND_DIR%/dist/kingfishair_frontend"

set JAR_FILE_NAME="angular-hotel-5.3-SNAPSHOT.jar"

set REMOTE_FRONTEND_DIR="~/frontend"

set REMOTE_BACKEND_DIR="~"

set REMOTE_STARTUP_SCRIPT="~/startup.sh"

set REMOTE_SHUTDOWN_SCRIPT="~/shutdown.sh"

:: Kill running process on server

echo ssh -i %PRIVATE_KEY_PATH% %SERVER_USER%@%SITE_DOMAIN% "%REMOTE_SHUTDOWN_SCRIPT%"
ssh -i %PRIVATE_KEY_PATH% %SERVER_USER%@%SITE_DOMAIN% %REMOTE_SHUTDOWN_SCRIPT%

:: Delete all existing frontend files

echo ssh -i %PRIVATE_KEY_PATH% %SERVER_USER%@%SITE_DOMAIN% "sudo rm -rf %REMOTE_FRONTEND_DIR%/*"

ssh -i %PRIVATE_KEY_PATH% %SERVER_USER%@%SITE_DOMAIN% "sudo rm -rf %REMOTE_FRONTEND_DIR%/*"

:: Copy frontend files

echo scp -i %PRIVATE_KEY_PATH% -r %FRONTEND_BUILD_DIR%/* %SERVER_USER%@%SITE_DOMAIN%:%REMOTE_FRONTEND_DIR%
scp -i %PRIVATE_KEY_PATH% -r %FRONTEND_BUILD_DIR%/* %SERVER_USER%@%SITE_DOMAIN%:%REMOTE_FRONTEND_DIR%

:: Copy backend files

echo scp -i %PRIVATE_KEY_PATH% -r %BACKEND_BUILD_DIR%/%JAR_FILE_NAME% %SERVER_USER%@%SITE_DOMAIN%:%REMOTE_BACKEND_DIR%

scp -i %PRIVATE_KEY_PATH% -r %BACKEND_BUILD_DIR%/%JAR_FILE_NAME% %SERVER_USER%@%SITE_DOMAIN%:%REMOTE_BACKEND_DIR%

:: Start backend server

echo ssh -i %PRIVATE_KEY_PATH% %SERVER_USER%@%SITE_DOMAIN% "%REMOTE_STARTUP_SCRIPT% %REMOTE_BACKEND_DIR%/%JAR_FILE_NAME%"

ssh -i %PRIVATE_KEY_PATH% %SERVER_USER%@%SITE_DOMAIN% "%REMOTE_STARTUP_SCRIPT% %REMOTE_BACKEND_DIR%/%JAR_FILE_NAME%"
